### ISSUE TITLE
Party always attacks enemies in reverse spawn order

### ISSUE THREAD

**Issue by Sudospective** [grifkuba/sota-issues#17]
**Location of bug:**
Ocean Planet
**Stack trace:**
`{function:submit_issue, line:19, source:res://Scripts/CrashHandler.gd}`
`{function:_on_Issue_submit, line:230, source:res://Scripts/GUI.gd}`
**Additional info:**
When there is more than one enemy in battle, party will always attack enemies in reverse order of when they spawned in.

**Comment by Clover10123** [comment]
I'm aware of this issue, and I'm pretty sure it's because of the way I handle priority values. I can address this problem.

**Comment by Moltak1** [comment]
I'm working on refactoring this code but not sure what the intended order is could I get a full explanation of the intended order? on the GDD it mentions the Priority value but has it at 0 anyway, there's also the courage value but it's not explained on the GDD

**Comment by Sudospective** [comment]
> I'm working on refactoring this code but not sure what the intended order is could I get a full explanation of the intended order? on the GDD it mentions the Priority value but has it at 0 anyway, there's also the courage value but it's not explained on the GDD

The intended order of this is not related to any priority other than the order of which they have spawned in battle. So if I click the first box, I should attack the first spawned enemy, if I click the third box, I should attack the third spawned enemy, etc.

**Comment by Sudospective** [comment]
im really handy with github issues goddamn
