### ISSUE TITLE
Attempt to call function "set_size" in base 'null instance' on a null instance.

### ISSUE THREAD

**Issue by Clover10123** [grifkuba/sota-issues#20]
**Describe the bug**

**To Reproduce**
1. Open the game, have no old save files.
2. Click on a new game save
3. Name your new character

**Expected behavior**
After naming your new character, a game starts

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version V.0.100 (You should be updating this number with every push to Master...)

**Additional context**

**Please attach `log.txt` to your bug report for faster assistance** (located in C:\Users\{username}\AppData\Roaming\Godot\app_userdata\Seekers-of-the-Aether)

my godot isn't located in C so idk where I'd find this tbh but the stack trace on godot is:
0 - res://Scripts/Managers/LevelManager.gd:10 - at function: _ready
1 - res://Scripts/Gameplay.gd:99 - at function: portal

![image](https://user-images.githubusercontent.com/25303291/115942827-b59a9a80-a471-11eb-9544-5332a4a4a392.png)

**Comment by Sudospective** [comment]
Fixed in V.0.201, recently pushed.
