### ISSUE TITLE
Invalid get index 'stats' [on base: 'previously freed instance'].

### ISSUE THREAD

**Issue by Clover10123** [grifkuba/sota-issues#21]
**Describe the bug**
Game crashes at the end of a battle.

**To Reproduce**
1. Start new game
2. Proceed through all of dialogue in beginning sequence
3. Go to Planet 1
4. Proceed through dialogue until the battle begins
5. Complete battle
6. See error

**Expected behavior**
Battle ends and we return to dialogue

**Screenshots**
![image](https://user-images.githubusercontent.com/25303291/116014609-b95a2880-a5fb-11eb-9f8f-57e4b7b334b6.png)

**Additional context**
Most likely the enemies are "dying" before stats are being calculated.

**Please attach `log.txt` to your bug report for faster assistance** (located in C:\Users\{username}\AppData\Roaming\Godot\app_userdata\Seekers-of-the-Aether)
0 - res://Scripts/Managers/BattleManager.gd:335 - at function: friendly_team_handler
1 - res://Scripts/Managers/BattleManager.gd:314 - at function: end_phase_handler

**Comment by Sudospective** [comment]
oh heck

well oof i guess ill have to figure this out on the train

**Comment by Sudospective** [comment]
The code for the battle system is currently being refactored and this issue will be easier to solve once most of the entity-specific functions are moved to a different manager.
