### ISSUE TITLE
Save file labels need to update the moment the save files are deleted

### ISSUE THREAD

**Issue by Clover10123** [grifkuba/sota-issues#22]
**Describe the bug**
When you delete a save file, the UI does not update with the correct information.

**To Reproduce**
1. Open game
2. Press Shift + F1, or F2, etc to delete a file
3. Press "Play"

**Expected behavior**
If a save file is deleted, a name should not appear.

**Comment by Moltak1** [comment]
Deleting saves with the save menu open doesn't delete the save since the data is already loaded

**Comment by Sudospective** [comment]
This is true. There should be an extra step that deletes the data from the global dictionary's save slot as well.

**Comment by Sudospective** [comment]
Fixed in recent push
