### ISSUE TITLE
Gameplay scene not properly initialized

### ISSUE THREAD

**Issue by Moltak1** [grifkuba/sota-issues#25]
**Describe the bug**
Gameplay scene is not properly initialized

The Gameplay scene expects nodes that are missing from the tree

```
onready var enemy = viewport.get_node("Enemy")
...
onready var lvl = viewport.get_node("Level")
onready var btl = viewport.get_node("Battleground")
```

**To Reproduce**
Code error no steps

**Expected behavior**
Level and Battleground are dynamically added in the portal function need to ensure they aren't used before they get added
Enemy never gets used

**Screenshots**
![k67a7qShDl](https://user-images.githubusercontent.com/23225775/116173404-28a24c00-a6d2-11eb-99c8-900d38abcc47.png)

![cEfgZn50Uu](https://user-images.githubusercontent.com/23225775/116173506-54253680-a6d2-11eb-933c-aa7c012632b9.png)

**Comment by Moltak1** [comment]
Related Second Issue

Samantha and Player are both initialized yet they get added in the Portal function

Gameplay.gd
```
func portal(new_level: String, afterscene: String = ""):
	...
	viewport.move_child(next_btl, 1)
	viewport.add_child(plr, true)
	viewport.add_child(ally, true)
	lvl = viewport.get_node("Level")
        ...
```

![vB1j3CfR3N](https://user-images.githubusercontent.com/23225775/116174498-2a6d0f00-a6d4-11eb-8677-552591279e81.png)

**Comment by Sudospective** [comment]
Should be fixed with new push.
