### ISSUE TITLE
Start scene is missing script / dangling signal

### ISSUE THREAD

**Issue by Moltak1** [grifkuba/sota-issues#26]
**Describe the bug**
Start scene area_entered connected but is missing a script file

*To Reproduce**
Code error

**Expected behavior**
Add missing script file or clear signal

**Screenshots**
![bXV46Sb1Ci](https://user-images.githubusercontent.com/23225775/116175240-8e440780-a6d5-11eb-86f7-a81ae9c32461.png)

![F4W2us2p7L](https://user-images.githubusercontent.com/23225775/116175367-ca776800-a6d5-11eb-9c3b-caa8fce0c795.png)

![KUaKVKHAu5](https://user-images.githubusercontent.com/23225775/116175373-ce0aef00-a6d5-11eb-9af5-95338fce78f5.png)

**Comment by Sudospective** [comment]
Things got messy when I was blowing through crunch time to get things finished before my move; this should be cleaned up at some point this week, thanks for the report

**Comment by Sudospective** [comment]
Fixed in recent push
